=== 555vedant/uPortal/uportal-war/src/main/resources/xsd/portlet-publishing/portlet-publishing-definition.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="https://source.jasig.org/schemas/uportal/portlet-publishing"
    targetNamespace="https://source.jasig.org/schemas/uportal/portlet-publishing"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:element name="portlet-publishing-definition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="step" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="step">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="preference" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="arbitrary-preferences" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="parameter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="label" type="xs:string" />
                <xs:element name="description" type="xs:string"
                    minOccurs="0" />
                <xs:element name="example" type="xs:string"
                    minOccurs="0" />
                <xs:element ref="parameter-input"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="preference">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="readOnly" type="xs:boolean"
                    default="false" minOccurs="0" />
                <xs:element name="label" type="xs:string" />
                <xs:element name="description" type="xs:string"
                    minOccurs="0" />
                <xs:element name="example" type="xs:string"
                    minOccurs="0" />
                <xs:element ref="preference-input"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="input-type" abstract="true"/>

    <xs:complexType name="preference-input-type" abstract="true">
        <xs:complexContent>
            <xs:extension base="input-type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="single-valued-preference-input-type" abstract="true">
        <xs:complexContent>
            <xs:extension base="preference-input-type">
                <xs:sequence>
                    <xs:element name="default" type="xs:string"
                        minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="multi-valued-preference-input-type" abstract="true">
        <xs:complexContent>
            <xs:extension base="preference-input-type">
                <xs:sequence>
                    <xs:element name="default" type="xs:string"
                        minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="preference-input" abstract="true" type="preference-input-type"/>

    <xs:element name="single-text-preference-input" substitutionGroup="preference-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="single-valued-preference-input-type">
                    <xs:attribute name="display" type="textDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="multi-text-preference-input" substitutionGroup="preference-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="multi-valued-preference-input-type">
                    <xs:attribute name="display" type="textDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="single-choice-preference-input" substitutionGroup="preference-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="single-valued-preference-input-type">
                    <xs:sequence>
                        <xs:element ref="option" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="display" type="singleChoiceDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="multi-choice-preference-input" substitutionGroup="preference-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="multi-valued-preference-input-type">
                    <xs:sequence>
                        <xs:element ref="option" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="display" type="multiChoiceDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="parameter-input-type" abstract="true">
        <xs:complexContent>
            <xs:extension base="input-type">
                <xs:sequence>
                    <xs:element name="default" type="xs:string"
                        minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="parameter-input" abstract="true" type="parameter-input-type"/>
    <xs:element name="single-text-parameter-input" substitutionGroup="parameter-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="parameter-input-type">
                    <xs:attribute name="display" type="textDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="single-choice-parameter-input" substitutionGroup="parameter-input">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="parameter-input-type">
                    <xs:sequence>
                        <xs:element ref="option" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="display" type="singleChoiceDisplay"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="option">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="textDisplay">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hidden"/>
            <xs:enumeration value="text" />
            <xs:enumeration value="textarea" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="singleChoiceDisplay">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hidden"/>
            <xs:enumeration value="select" />
            <xs:enumeration value="radio" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="multiChoiceDisplay">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hidden"/>
            <xs:enumeration value="select" />
            <xs:enumeration value="checkbox" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== 555vedant/uPortal/uportal-war/src/main/resources/org/jasig/portal/portlets/CMS/AdvancedCMSPortlet.cpd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed to Jasig under one or more contributor license agreements. See the 
    NOTICE file distributed with this work for additional information regarding copyright 
    ownership. Jasig licenses this file to you under the Apache License, Version 2.0 
    (the "License"); you may not use this file except in compliance with the License. 
    You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0 
    Unless required by applicable law or agreed to in writing, software distributed under 
    the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
    OF ANY KIND, either express or implied. See the License for the specific language 
    governing permissions and limitations under the License. -->

<portlet-publishing-definition
    xmlns="https://source.jasig.org/schemas/uportal/portlet-publishing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/portlet-publishing ../../../../../xsd/portlet-publishing/portlet-publishing-definition.xsd">

    <step>

        <name>Portlet Descriptor</name>

        <description>
            Enter the Portlet web-application path and portlet name.
        </description>

        <parameter>
            <name>isFrameworkPortlet</name>
            <label>Framework Portlet</label>
            <description>
              Portlet is deployed in the same web-application as uPortal. If checked "Portlet Web Application Path"
              is ignored.
            </description>
            <single-choice-parameter-input>
                <default>true</default>
                <option value="true" label="true" />
                <option value="false" label="false" />
            </single-choice-parameter-input>
        </parameter>

        <parameter>
            <name>portletApplicationId</name>
            <label>Portlet Web Application Path</label>
            <description>
              This is the name of the web application the portlet resides in including a preceding /.
            </description>
            <example>/pluto-testsuite</example>
            <single-text-parameter-input>
                <default>/SimpleContentPortlet</default>
            </single-text-parameter-input>
        </parameter>

        <parameter>
            <name>portletName</name>
            <label>Portlet Name</label>
            <description>
              This is the name of the portlet as defined in the portlet.xml descriptor.
            </description>
            <example>test-port-et-1</example>
            <single-text-parameter-input>
                <default>cms</default>
            </single-text-parameter-input>
        </parameter>

        <parameter>
            <name>disableDynamicTitle</name>
            <label>Disable Dynamic Title</label>
            <description>
              Disable dynamic title
            </description>
            <example>false</example>
            <single-choice-parameter-input>
                <default>true</default>
                <option value="true" label="true" />
                <option value="false" label="false" />
            </single-choice-parameter-input>
        </parameter>

        <preference>
            <name>cleanContent</name>
            <label>Clean Content</label>
            <description>
              Clean content
            </description>
            <example>false</example>
            <single-choice-preference-input>
                <default>false</default>
                <option value="true" label="true" />
                <option value="false" label="false" />
            </single-choice-preference-input>
        </preference>

    </step>

</portlet-publishing-definition>
