=== 555vedant/uPortal/uportal-impl/src/main/resources/dtd/channelDefinition.dtd
<!--

    Copyright (c) 2000-2009, Jasig, Inc.
    See license distributed with this file and available online at
    https://www.ja-sig.org/svn/jasig-parent/tags/rel-10/license-header.txt

-->
<!ELEMENT channel-definition (channelId?,title, name, fname, desc, type, class, timeout, hasedit, hashelp, hasabout, secure, locale, categories, groups, users?, parameters?, portletPreferences?, makeFNameAccessibleOnly? )>
<!ATTLIST channel-definition script CDATA #IMPLIED>

<!ELEMENT categories (category)*>

<!ELEMENT groups (group)*>

<!ELEMENT users (user)*>

<!ELEMENT parameters (parameter)*>
<!ELEMENT parameter (name, value, description, ovrd)>

<!ELEMENT portletPreferences (portletPreference)*>
<!ELEMENT portletPreference (name, read-only?, values?)>
<!ELEMENT values (value)*>

<!ELEMENT makeFNameAccessibleOnly EMPTY>
<!ELEMENT channelId (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT hasedit (#PCDATA)>
<!ELEMENT hashelp (#PCDATA)>
<!ELEMENT hasabout (#PCDATA)>
<!ELEMENT secure (#PCDATA)>
<!ELEMENT locale (#PCDATA)>

<!ELEMENT category (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT user (#PCDATA)>

<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT ovrd (#PCDATA)>
<!ELEMENT read-only (#PCDATA)>

=== 555vedant/uPortal/properties/chanpub/test-portlet-1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<channel-definition>

    <title>Test Portlet 1</title>
    <name>Test Portlet 1</name>
    <fname>test-portlet-1</fname>
    <desc>Test portlet 1 from Apache Pluto</desc>
    <type>Custom</type>
    <class>org.jasig.portal.channels.portlet.CPortletAdapter</class>
    <timeout>60000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>N</hashelp>
    <hasabout>N</hasabout>

    <secure>N</secure>
    <locale>en_US</locale>
    
    <categories>
        <category>Development</category>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters>

        <parameter>
            <name>portletDefinitionId</name>
            <value>testsuite.TestPortlet1</value>
            <description>Identifies the portlet deployed within the portlet container</description>
            <ovrd>N</ovrd>
        </parameter>

    </parameters>
    
</channel-definition>

=== 555vedant/uPortal/properties/chanpub/google-portlet.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<!-- You can download this Google Sample Portlet from the Portlet Open Source Trading site (POST).
     http://portlet-opensrc.sourceforge.net/
     http://prdownloads.sourceforge.net/portlet-opensrc/GooglePortlet.zip?download
-->
    
<channel-definition>

    <title>Google Portlet</title>
    <name>Google Portlet</name>
    <fname>google-portlet</fname>
    <desc>Google Portlet from Portlet Open Source Trading site</desc>
    <type>Portlet</type>
    <class>org.jasig.portal.channels.portlet.CPortletAdapter</class>
    <timeout>60000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>Y</hashelp>
    <hasabout>N</hasabout>

    <secure>N</secure>
    <locale>en_US</locale>
    
    <categories>
        <category>Development</category>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters>

        <!-- The syntax of the ID is [portlet-context-name].[portlet-name] -->
        <parameter>
            <name>portletDefinitionId</name>
            <value>GooglePortlet.GooglePortlet</value>
            <description>Identifies the portlet deployed within the portlet container</description>
            <ovrd>N</ovrd>
        </parameter>

    </parameters>
    
</channel-definition>

=== 555vedant/uPortal/properties/chanpub/chandefs/daily-business-cartoon.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<channel-definition>

    <title>Daily Business Cartoon</title>
    <name>Account Request</name>
    <fname>ibs-account-request</fname>
    <desc>Lets people request an account for uPortal.biz. The request
        will be     sent as an email to the portal administrator and the
        person that requested     the account will receive a
        confirmation email.</desc>
    <type>Custom</type>
    <class>com.interactivebusiness.accountrequest.channel.CAccountRequest</class>
    <timeout>30000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>N</hashelp>
    <hasabout>N</hasabout>
    
    <categories>
        <category>Applications</category>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters>
    
        <parameter>
            <name>SMTPServer</name>
            <value>mail.interactivebusiness.com</value>
            <description>The SMTP server address</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>SenderUserName</name>
            <value>wrybicki</value>
            <description>The sender user name</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>SenderPassword</name>
            <value>ibsuser</value>
            <description>The sender password</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>SenderEmail</name>
            <value>upbiz-account-request@interactivebusiness.com</value>
            <description>The sender email address</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>AdminEmail</name>
            <value>mjerdely@interactivebusiness.com,kweiner@interactivebusiness.com</value>
            <description>The administrator email address</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>EmailSubjectLineToAdmin</name>
            <value>New uPortal.biz account request</value>
            <description>The subject line of the email sent to the administrator</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>EmailSubjectLineToRequestor</name>
            <value>Information about your uPortal.biz account request</value>
            <description>The subject line of the email sent to the requestor</description>
            <ovrd>N</ovrd>
        </parameter>
        
        <parameter>
            <name>DaysToWaitForAccount</name>
            <value>2</value>
            <description>Days to wait for an account</description>
            <ovrd>N</ovrd>
        </parameter>
        
    </parameters>
    
</channel-definition>

=== 555vedant/uPortal/properties/chanpub/fragment-manager.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<channel-definition>

    <title>Fragment Manager</title>
    <name>Fragment Manager</name>
    <fname>fragment-manager</fname>
    <desc>The fragment constructor/publisher channel</desc>
    <type>Custom</type>
    <class>org.jasig.portal.layout.channels.CFragmentManager</class>
    <timeout>5000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>N</hashelp>
    <hasabout>N</hasabout>

    <secure>N</secure>
    <locale>en_US</locale>
    
    <categories>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters/>
    
</channel-definition>
