=== 555vedant/uPortal/uportal-war/src/main/resources/xsd/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-types.xsd"/>

    <xs:element name="stylesheet-descriptor">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="io:basePortalDataType">
                    <xs:sequence>
                        <xs:element name="name" type="io:fname-type"/>
                        <xs:element name="description" type="xs:string" minOccurs="0"/>
                        <xs:element name="uri" type="xs:string"/>
                        <xs:element name="output-property" type="externalOutputPropertyDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                        <xs:element name="stylesheet-parameter" type="externalStylesheetParameterDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                        <xs:element name="layout-attribute" type="externalLayoutAttributeDescriptor" minOccurs="0"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                    
                    <xs:attribute name="version" type="io:version40Type" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="unique-output-property">
            <xs:selector xpath="output-property"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-stylesheet-parameter">
            <xs:selector xpath="stylesheet-parameter"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-layout-attribute">
            <xs:selector xpath="layout-attribute"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalOutputPropertyDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="externalStylesheetParameterDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="externalLayoutAttributeDescriptor">
        <xs:complexContent>
            <xs:extension base="externalStylesheetData">
                <xs:sequence>
                    <xs:element name="targetElement" type="xs:NCName" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="externalStylesheetData">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="default-value" type="xs:string" minOccurs="0"/>
            <xs:element name="scope" type="externalStylesheetDataScope"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="externalStylesheetDataScope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PERSISTENT"/>
            <xs:enumeration value="SESSION"/>
            <xs:enumeration value="REQUEST"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 555vedant/uPortal/uportal-war/src/test/resources/org/jasig/portal/io/xml/ssd/test_4-0.stylesheet-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<stylesheet-descriptor
    xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor"
    xmlns:ns2="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0"
    xsi:schemaLocation="
        https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd"
>
    <name>DLMXHTML</name>
    <description>Renders DLMTabsColumns as xhtml</description>
    <uri>classpath:/layout/theme/universality/universality.xsl</uri>
    <url-syntax-helper>MultiTabSyntaxHelper</url-syntax-helper>
    <output-property>
        <name>mime-type</name>
        <scope>PERSISTENT</scope>
        <description>The mime type the stylesheet outputs</description>
    </output-property>
    <stylesheet-parameter>
        <name>skin</name>
        <default-value>uportal3</default-value>
        <scope>PERSISTENT</scope>
        <description>Skin name</description>
    </stylesheet-parameter>
    <layout-attribute>
        <name>minimized</name>
        <default-value>false</default-value>
        <scope>PERSISTENT</scope>
        <description>Flag determining if the channel is minimized or not</description>
        <targetElement>channel</targetElement>
    </layout-attribute>
</stylesheet-descriptor>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/stylesheet-descriptor/UniversalityMobile-theme.stylesheet-descriptor.xml
<stylesheet-descriptor
    xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor ../../../resources/xsd/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd"
   
    version="4.0"
>
    <name>UniversalityMobile</name>
    <description>Renders DLMTabsColumns as xhtml for a mobile device</description>
    <uri>classpath:/layout/theme/muniversality/muniversality.xsl</uri>
    <stylesheet-parameter>
      <name>skin</name>
      <default-value>iphone</default-value>
      <scope>PERSISTENT</scope>
      <description>Skin name</description>
    </stylesheet-parameter>
    <layout-attribute>
      <name>minimized</name>  
      <default-value>false</default-value>  
      <scope>PERSISTENT</scope>
      <description>Flag determining if the channel is minimized or not</description>  
      <targetElement>channel</targetElement>  
    </layout-attribute>
</stylesheet-descriptor>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/stylesheet-descriptor/UniversalityAndroid-theme.stylesheet-descriptor.xml
<stylesheet-descriptor
    xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor ../../../resources/xsd/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd"
   
    version="4.0"
>
    <name>UniversalityAndroid</name>
    <description>Renders DLMTabsColumns as xhtml for a mobile device</description>
    <uri>classpath:/layout/theme/muniversality/muniversality.xsl</uri>
    <stylesheet-parameter>
        <name>minimizePortletsDefault</name>
        <default-value>true</default-value>
        <scope>REQUEST</scope>
        <description>Overloading the use of the stylesheet parameters to denote that portlets should render minimized by default for this stylesheet</description>
    </stylesheet-parameter>
    <stylesheet-parameter>
      <name>skin</name>
      <default-value>android</default-value>
      <scope>PERSISTENT</scope>
      <description>Skin name</description>
    </stylesheet-parameter>
</stylesheet-descriptor>

=== 555vedant/uPortal/uportal-war/src/main/data/required_entities/stylesheet-descriptor/DLMXHTML-theme.stylesheet-descriptor.xml
<stylesheet-descriptor
    xmlns="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor ../../../resources/xsd/io/stylesheet-descriptor/stylesheet-descriptor-4.0.xsd"
   
    version="4.0"
>
    <name>DLMXHTML</name>
    <description>Renders DLMTabsColumns as xhtml</description>
    <uri>classpath:/layout/theme/universality/universality.xsl</uri>
    <stylesheet-parameter>
      <name>skin</name>
      <default-value>uportal3</default-value>
      <scope>PERSISTENT</scope>
      <description>Skin name</description>
    </stylesheet-parameter>
</stylesheet-descriptor>
