=== 555vedant/uPortal/uportal-war/src/main/resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-types.xsd"/>

    <xs:element name="portlet-definition" type="externalPortletDefinition">
        <xs:unique name="unique-category">
            <xs:selector xpath="category"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-group">
            <xs:selector xpath="group"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-user">
            <xs:selector xpath="user"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-parameter">
            <xs:selector xpath="parameter"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-preference">
            <xs:selector xpath="portlet-preference"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalPortletDefinition">
        <xs:complexContent>
            <xs:extension base="io:basePortalDataType">
                <xs:sequence>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="fname" type="io:fname-type"/>
                    <xs:element name="desc" type="xs:string" minOccurs="0"/>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="timeout" type="xs:positiveInteger"/>

                    <xs:element name="portlet-descriptor" type="portlet-descriptor"/>

                    <xs:element name="category" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="group" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="user" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="parameter" type="externalPortletParameter" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="portlet-preference" type="externalPortletPreference" minOccurs="0"
                        maxOccurs="unbounded"/>
                </xs:sequence>

                <xs:attribute name="version" type="io:version40Type" use="required"/>

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="portlet-descriptor">
        <xs:sequence>
            <xs:choice>
                <xs:element name="isFramework" type="xs:boolean" fixed="true" />
                <xs:element name="webAppName" type="xs:string"/>
            </xs:choice>
            <xs:element name="portletName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="externalPortletParameter">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="externalPortletPreference">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="readOnly" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/notifications.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>My Notifications</title>
  <name>My Notifications</name>
  <fname>notifications</fname>
  <desc>Mockup notifications portlet.</desc>
  <type>CMS</type>
  <timeout>10000</timeout>
  <portlet-descriptor xmlns:up="https://source.jasig.org/schemas/uportal">
    <up:webAppName>/SimpleContentPortlet</up:webAppName>
    <up:portletName>cms</up:portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Information</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/preferences-desktop-multimedia.png</value>
    </parameter>
  
  
    <portlet-preference>
        <name>content</name>
        <value>
            <![CDATA[
                <img src="/uPortal/media/org/jasig/portal/channels/webproxy/notifications.png" 
                alt="uP3 Mock Notifications" border="0" />
                <p>Mock of the <a href="http://www.unicon.net/node/675">Toro 
                Notifications Portlet</a> by <a href="http://www.unicon.net/">
                Unicon</a>.  This is a sample screen for demonstration purposes only.</p>
            ]]>
        </value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/passwordmgr.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
    script="classpath://org/jasig/portal/io/jaxb-import_v4-0.crn"
    version="4.0"
>

  <title>Password Management</title>
  <name>Password Management</name>
  <fname>passwordmgr</fname>
  <desc>Allows management of passwords.</desc>
  <type>Portlet</type>
  <timeout>50000</timeout>
  <portlet-descriptor>
    <isFramework>true</isFramework>
    <portletName>SelfEditAccount</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>uPortal</category>
  
  
    <group>Faculty</group>
    <group>Staff</group>
    <group>Students</group>
  
  
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/categories/preferences-system.png</value>
    </parameter>
  
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/reset-password.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
    version="4.0">

    <title>Reset Password</title>
    <name>Reset Password</name>
    <fname>reset-password</fname>
    <desc>Reset a forgotten password</desc>
    <type>Portlet</type>
    <timeout>30000</timeout>
    <portlet-descriptor>
        <isFramework>true</isFramework>
        <portletName>ResetPassword</portletName>
    </portlet-descriptor>
    <group>Everyone</group>
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/e-online.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>E! Online</title>
  <name>E! Online</name>
  <fname>e-online</fname>
  <desc>Recent news from E! Online.</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor xmlns:up="https://source.jasig.org/schemas/uportal">
    <up:webAppName>/NewsReaderPortlet</up:webAppName>
    <up:portletName>single-feed-news</up:portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Entertainment</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>E! Online</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://feeds.eonline.com/EOnline-WhatsHot</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/jasig-news.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>Jasig News</title>
  <name>Jasig News</name>
  <fname>jasig-news</fname>
  <desc>Jasig News channel</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>News</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>Jasig News</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://jasig.org/jasig-news/feed</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/chronicle-wired.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>The Chronicle: Wired Campus</title>
  <name>The Chronicle: Wired Campus</name>
  <fname>chronicle-wired</fname>
  <desc>Top stories from The Chronicle of Higher Education: Wired Campus Edition</desc>
  <type>RSS</type>
  <timeout>5000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Entertainment</category>
    <category>News</category>
  
  
    <group>Everyone</group>
  
  
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
    <parameter>
        <name>mobileIconUrl</name>
        <value>/uPortal/media/skins/icons/mobile/feed.png</value>
    </parameter>
    <parameter>
        <name>editable</name>
        <value>true</value>
    </parameter>
    <parameter>
        <name>hasHelp</name>
        <value>true</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>The Chronicle: Wired Campus</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://chronicle.com/blog/Wired-Campus/5/rss</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/word-of-the-day.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>Word of the Day</title>
  <name>Word of the Day</name>
  <fname>word-of-the-day</fname>
  <desc>Word of the Day channel</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Entertainment</category>
  
  
    <group>Everyone</group>
  
  
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>Word of the Day</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://www.dictionary.com/wordoftheday/wotd.rss</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>full</value>
    </portlet-preference>
    <portlet-preference> 
      <name>maxStories</name>
      <value>1</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/test/resources/org/jasig/portal/io/xml/portlet/groupsmanager_32-40_expected.channel.xml
<?xml version="1.0" encoding="UTF-8"?>
<portlet-definition xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition https://source.jasig.org/schemas/uportal/io/portlet-definition/portlet-definition-4.0.xsd" version="4.0">
<ns11:title xmlns:ns11="https://source.jasig.org/schemas/uportal/io/portlet-definition">Groups Manager</ns11:title>
<ns12:name xmlns:ns12="https://source.jasig.org/schemas/uportal/io/portlet-definition">Groups Manager</ns12:name>
<ns13:fname xmlns:ns13="https://source.jasig.org/schemas/uportal/io/portlet-definition">groupsmanager</ns13:fname>
<ns14:desc xmlns:ns14="https://source.jasig.org/schemas/uportal/io/portlet-definition">An administrative tool for creating and managing groups and memberships</ns14:desc>
<ns15:type xmlns:ns15="https://source.jasig.org/schemas/uportal/io/portlet-definition">Custom</ns15:type>
<ns16:timeout xmlns:ns16="https://source.jasig.org/schemas/uportal/io/portlet-definition">40000</ns16:timeout>
    <ns17:category xmlns:ns17="https://source.jasig.org/schemas/uportal/io/portlet-definition">Applications</ns17:category>
  
    <ns18:group xmlns:ns18="https://source.jasig.org/schemas/uportal/io/portlet-definition">Portal Administrators</ns18:group>
    <ns19:group xmlns:ns19="https://source.jasig.org/schemas/uportal/io/portlet-definition">Developers</ns19:group>
  <parameter>
<name>hasedit</name>
<value>false</value>
</parameter>
<parameter>
<name>hashelp</name>
<value>false</value>
</parameter>
<parameter>
<name>hasabout</name>
<value>false</value>
</parameter>
<parameter>
<name>secure</name>
<value>false</value>
</parameter>
<parameter>
<name>locale</name>
<value>false</value>
</parameter>
</portlet-definition>
