=== 555vedant/uPortal/uportal-war/src/main/resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-types.xsd"/>

    <xs:element name="portlet-definition" type="externalPortletDefinition">
        <xs:unique name="unique-category">
            <xs:selector xpath="category"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-group">
            <xs:selector xpath="group"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-user">
            <xs:selector xpath="user"/>
            <xs:field xpath="."/>
        </xs:unique>
        <xs:unique name="unique-parameter">
            <xs:selector xpath="parameter"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="unique-preference">
            <xs:selector xpath="portlet-preference"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalPortletDefinition">
        <xs:complexContent>
            <xs:extension base="io:basePortalDataType">
                <xs:sequence>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="fname" type="io:fname-type"/>
                    <xs:element name="desc" type="xs:string" minOccurs="0"/>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="timeout" type="xs:positiveInteger"/>

                    <xs:element name="portlet-descriptor" type="portlet-descriptor"/>

                    <xs:element name="category" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="group" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="user" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="parameter" type="externalPortletParameter" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="portlet-preference" type="externalPortletPreference" minOccurs="0"
                        maxOccurs="unbounded"/>
                </xs:sequence>

                <xs:attribute name="version" type="io:version40Type" use="required"/>

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="portlet-descriptor">
        <xs:sequence>
            <xs:choice>
                <xs:element name="isFramework" type="xs:boolean" fixed="true" />
                <xs:element name="webAppName" type="xs:string"/>
            </xs:choice>
            <xs:element name="portletName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="externalPortletParameter">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="externalPortletPreference">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="readOnly" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/new-movies.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>Movies.com New This Week in Theaters</title>
  <name>Movies.com New This Week in Theaters</name>
  <fname>new-movies</fname>
  <desc>New movies opening this week from Movies.com</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Entertainment</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/mimetypes/video-x-generic.png</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>Movies.com New in Theaters</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://movies.go.com/xml/rss/intheaters.xml</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/courses.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>My Courses</title>
  <name>My Courses</name>
  <fname>courses</fname>
  <desc>Mock course info portlet.</desc>
  <type>CMS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/SimpleContentPortlet</webAppName>
    <portletName>cms</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Academics</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/mimetypes/x-office-document.png</value>
    </parameter>
  
  
    <portlet-preference>
        <name>content</name>
        <value>
            <![CDATA[
                <img src="/uPortal/media/org/jasig/portal/channels/webproxy/mycourses.png" 
                alt="uP3 Mock Notifications" border="0" />
                
                <p>Mock of the <a href="http://code.google.com/p/my-courses-portlet/">
                My Courses Portlet</a> by <a href="http://www.unicon.net/">Unicon</a>.  
                This is a sample screen for demonstration purposes only.</p>
            ]]>
        </value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/about-college-life.portlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>About.com College Life</title>
  <name>About.com College Life</name>
  <fname>about-college-life</fname>
  <desc>About.com College Life RSS feed</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
    <category>Entertainment</category>
    <category>News</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
  
    <portlet-preference> 
      <name>name</name>
      <value>About.com College Life</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://z.about.com/6/g/collegelife/b/rss2.xml</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/please-register.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
    script="classpath://org/jasig/portal/io/jaxb-import_v4-0.crn"
    version="4.0"
>

  <title>Please Register</title>
  <name>Please Register</name>
  <fname>please-register</fname>
  <desc>uPortal registration message.</desc>
  <type>CMS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/SimpleContentPortlet</webAppName>
    <portletName>cms</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Information</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/mimetypes/text-html.png</value>
    </parameter>
  
  
    <portlet-preference>
        <name>content</name>
        <value>
            <![CDATA[
                <h2>Please register</h2>
                
                <p>
                    Please <a href="http://www.jasig.org/uportal/deployments" 
                    target="_blank">list your deployment of uPortal alongside 
                    the many others already registered</a> so that the many 
                    people who have made uPortal possible can know that their 
                    code is working for you as well.
                </p>
            ]]>
        </value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/login.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
    version="4.0">

    <title>Log In</title>
    <name>Log In</name>
    <fname>login</fname>
    <desc>Login form for local portal authentication</desc>
    <type>Portlet</type>
    <timeout>30000</timeout>
    <portlet-descriptor xmlns:up="https://source.jasig.org/schemas/uportal">
        <up:isFramework>true</up:isFramework>
        <up:portletName>Login</up:portletName>
    </portlet-descriptor>
    <group>Everyone</group>
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/phd-comics.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>PHD Comics</title>
  <name>PHD Comics</name>
  <fname>phd-comics</fname>
  <desc>Latest PHD Comics strip</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Entertainment</category>
  
  
    <group>Everyone</group>
  
  
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/emotes/face-smile.png</value>
    </parameter>
    <parameter>
        <name>mobileIconUrl</name>
        <value>/uPortal/media/skins/icons/mobile/feed.png</value>
    </parameter>
    <parameter>
        <name>editable</name>
        <value>true</value>
    </parameter>
    <parameter>
        <name>hasHelp</name>
        <value>true</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>PhD Comics</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://www.phdcomics.com/gradfeed.php</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>full</value>
    </portlet-preference>
    <portlet-preference> 
      <name>maxStories</name>
      <value>1</value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/whos-online.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
   
    version="4.0"
>

  <title>Who's Online</title>
  <name>Who's Online</name>
  <fname>whos-online</fname>
  <desc>Mockup of a Who's Online portlet.</desc>
  <type>CMS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/SimpleContentPortlet</webAppName>
    <portletName>cms</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>Information</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/mimetypes/text-html.png</value>
    </parameter>
  
  
    <portlet-preference>
        <name>content</name>
        <value>
            <![CDATA[
                <img src="/uPortal/media/org/jasig/portal/channels/webproxy/whosonline.png" 
                alt="uP3 Mock My Courses" border="0" />
                
                <p>Mock of Who's Online.  This is a sample screen for 
                demonstration purposes only.</p>
                
            ]]>
        </value>
    </portlet-preference>
  
</portlet-definition>

=== 555vedant/uPortal/uportal-war/src/main/data/default_entities/portlet/ny-times.portlet.xml
<portlet-definition
    xmlns="https://source.jasig.org/schemas/uportal/io/portlet-definition" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/portlet-definition ../../../resources/xsd/io/portlet-definition/portlet-definition-4.0.xsd"
    script="classpath://org/jasig/portal/io/jaxb-import_v4-0.crn"
    version="4.0"
>

  <title>NY Times</title>
  <name>NY Times</name>
  <fname>ny-times</fname>
  <desc>Recent news from the NY Times</desc>
  <type>RSS</type>
  <timeout>10000</timeout>
  <portlet-descriptor>
    <webAppName>/NewsReaderPortlet</webAppName>
    <portletName>single-feed-news</portletName>
  </portlet-descriptor>
  
  
  
  
    <category>News</category>
  
  
    <group>Everyone</group>
  
  
    <parameter>
      <name>disableDynamicTitle</name>
      <value>true</value> 
    </parameter>
	<parameter>
      <name>iconUrl</name>
      <value>/ResourceServingWebapp/rs/tango/0.8.90/32x32/apps/internet-news-reader.png</value>
    </parameter>
  
  
    <portlet-preference> 
      <name>name</name>
      <value>New York Times</value>
    </portlet-preference>
    <portlet-preference> 
      <name>url</name>
      <value>http://feeds.nytimes.com/nyt/rss/HomePage</value>
    </portlet-preference>
    <portlet-preference> 
      <name>summaryView</name>
      <value>flyout</value>
    </portlet-preference>
  
</portlet-definition>
